### ISSUE TITLE
question on style ordering

### ISSUE THREAD

**Issue by agrady42** [blakeembrey/react-free-style#17]
Apologies if I'm missing something in the docs I couldn't find - is there a reasonable way to control the order of the classes output? Maybe a better question is how to predict which styles will be applied due to css cascading, since given equal specificity, the last style applied (of a given style type) is the one rendered.

Example: I have a react component for a progress bar with a class applied using free-style. I'm trying to add an optional prop to add another class, should the parent want to override/add some styles. The parent component registers the style with free-style and passes the classname (generated with Style.registerStyle()) as a prop to the progress bar. I use Style.join() to get the actual string used for the className in the progress bar.

The intention is to allow a parent component's class(es) to override some (but not necessarily all) of the styles on a given component.

At the moment my options seem to be:
- replace the class with the one provided. I don't like this because the parent has to know the styles they don't want to override.
- use in-line styles passed from the parent. defeats a good part of the purpose of free-style
- use !important. yuck.

Any other ideas?

**Comment by blakeembrey** [comment]
The styles are output in the order that they are created. Later created styles will be further down the CSS output than earlier styles. It's really just a list that's getting a appended to for that (though styles that compute to the same hash currently get appended back to the end).

Inline styles here aren't terrible, but yes - let's try to find a solution without that. Replacing the class is lame. Never use `!important`, agree. So, the main solution - according to the rules above - would be to generate a new class from the passed in styles. Unfortunately I haven't been using React for a while, but I think the ideal solution would be to have a method on the context that allows for generating styles in the render loop which automatically detach each re-render. Previously this was actually a feature, though I never worked out how to 100% automate it - you had to create the style on `componentWillMount` and remove the style with `componentWillUnmount`. It should still work, if you know the trick of accessing the context and creating a style during mount.

However, I'd love to improve this. You're probably in a better position to fix it, so if you find it I'd love help 😄 For reference, I think the implementation would look something like:

1. Each time a render occurs, create a `new FreeStyle` and merge it with the current free style instance
2. Somehow pass that into the rendering component (whatever the current pattern is?)
3. On unmount, unmerge the render free style instance from the current free style instance (this will delete the style diff automatically)

Some thoughts:

* For the created instance each render, maybe it's a flag for the component wrapper like `{ style: true }` that will create a getter on the props of `freeStyle` - when got the first time, it'll create the instance and set up the above steps
* The issue I had here in the past was actually creating styles - since you can't modify the React tree during render I couldn't create any styles in the same loop - you probably have a better idea than me, but the easy workaround is to make rendering styles a `nextTick` action after the first render - thoughts?

**Comment by agrady42** [comment]
Thanks for the thorough response! Off the top of my head most of that makes a lot of sense. I will definitely take a crack at it, though I can't say how soon I'll be able to get to it (this week if I'm lucky). Hopefully it's just me waiting on it then:) I'll report back with a proposal when I can.

**Comment by blakeembrey** [comment]
This has been implemented in `4.0.0` - you can register dynamic styles in only the current render loop.
