### ISSUE TITLE
HOC example is not clear or does not work

### ISSUE THREAD

**Issue by sladiri** [blakeembrey/react-free-style#29]
[the readme example](https://github.com/blakeembrey/react-free-style#hoc) suggests to me that I can access the `html` style inside my component as `styles.html`. But there is only `styles.button` available. The registerCss call seems to do nothing.
Is this expected? Thanks.

**Comment by blakeembrey** [comment]
I'm not sure where it suggests that, but the `registerCss` is "registering CSS". What exactly do you expect to do with `html` CSS?

**Comment by blakeembrey** [comment]
Here's the function from the `free-style` docs: https://github.com/blakeembrey/free-style#css-object. Let me know if that clears it up.

**Comment by sladiri** [comment]
I see, I have probably misunderstood how to use it. I will have a look at the docs of free-style. :)

**Comment by blakeembrey** [comment]
All good. I updated the example, let me know if it makes more sense now.

**Comment by sladiri** [comment]
I forgot to add what I wanted to do with 'html'.
What I expected was, that it would work like this, but it only works for classA:
```js
const withStyle = styled({
  classA: {
    color: 'red'
  }
})

withStyle.Style.registerCss({
  classB: {
    color: 'blue'
  }
})

export default withStyle(props => {
  return <div className={props.styles.classA}
      <button className={props.styles.classB}>Test</button>
    </div>
})
```
Now I see that I can use `className="classB"`, but is there a way to do the above, or am I using free-style wrong? Sorry, but I am not very experienced with CSS patterns.

**Comment by sladiri** [comment]
Would this approach be possible:
I create one HOC `withStyle` as in the examples for my parent component. I then pass `{styles, Styles: withStyle.Style}` to the child components, where they register their CSS on that instance.
There is no context involved, as the example suggests, and it would play nicely with any framework, since the style instance could be passed as a prop, instead of in context?

Is this possible? Thanks.

**Comment by blakeembrey** [comment]
It sounds like you're trying to add styles at render of the component, and that's really what the `context` is used for. Otherwise the `<style />` won't be reacting to your changes until the following render. Having the styles outside the render loop is definitely better for performance (running once vs running every mount).

To specifically do what you mentioned above, you could do:

```ts
withStyle.styles.classB = withStyle.Style.registerStyle({
  color: 'blue'
})
```

However, this is not for runtime as your second comment alluded to. I'd recommend taking some time to better prove out what you're trying to do and come back. I have some ideas, but I can't 100% tell if it's the same. Here's one thought though:

```
import { registerStyleSheet, styled } from 'react-free-style'

const ExternalComponent = Object.assign(props => {
  return <div className={props.styles.button} />
}, {
  styles: {
    button: {
      color: 'red'
    }
  }
})

const withStyle = styled()
const styles = registerStyleSheet(withStyle.Style, ExternalComponent.styles)

const MyComponent = withStyle(props => {
  return <ExternalComponent styles={styles} />
})
```

Not sure if that gets closer, but you can define styles on the component and allow anything importing it to do whatever it wants with those styles (e.g. this lib or another CSS-in-JS lib). Then, accept either a class name or a map of class names back on the component. There's some additional features with this approach - namely people could customise the styles based on your exported ones and pass different styles in as class names.

**Comment by sladiri** [comment]
Thank you, this example made it more clear to me. I was a bit lost with the various patterns out there (atomic CSS for example), and their relation to this module.
